### ISSUE TITLE
Java class can not be find when preparing the dataset.

### ISSUE THREAD

**Issue by swordfate** [SJTU-IPADS/gnnlab#1]
After I executed the following commands.
```
bash twitter.sh
bash uk-2006-05.sh
```
The same error occurs as follows.
```
Error: Could not find or load main class it.unimi.dsi.webgraph.BVGraph
Error: Could not find or load main class ipads.samgraph.webgraph.WebgraphDecoder
```
I don't know much about the Java language. How can I solve this problem? I will be very grateful if you could give any hints.

**Comment by molamooo** [comment]
Sorry, there is a missing step in data gen. Go to `utility/webgraph` and execute `mvn clean package`. It is required to properly installe maven & jdk. A successful build should generate `utility/webgraph/target/webgraph-0.1-SNAPSHOT.jar` file.

**Comment by swordfate** [comment]
> Sorry, there is a missing step in data gen. Go to `utility/webgraph` and execute `mvn clean package`. It is required to properly installe maven & jdk. A successful build should generate `utility/webgraph/target/webgraph-0.1-SNAPSHOT.jar` file.

It works! 
And when I executed `bash twitter.sh`, another error occurs: `../utility/data-process/build/coo-to-dataset: No such file or directory`. Then, I enter `utility/data-process/build` to execute `make` and `cooto-dataset` exists now.
Thanks for solving my question quickly, I will close this Issue since it has been solved.

**Comment by Krith-man** [comment]
Hello, I tried the same it worked. However, for Twitter and UK datasets there are no features and labels produced files. Where are they? In table 3 of your paper you count the feature size to 40GB and 74GB respectively but no such file was produced.

**Comment by lixiaobai09** [comment]
Because the original dataset has no feature data, we fill "zero" to all features for them in the dataset loading step.

As an example of DGL dataset loading, you can see line 73 in the file `utility/fastgraph/fastgraph/dataset_loader.py`.

As for samgraph, you can see L138 in the file `samgraph/common/engine.cc`.
