### ISSUE TITLE
How does gnnlab implement neighbor sampling for GCN models in CUDA?

### ISSUE THREAD

**Issue by BearBiscuit05** [SJTU-IPADS/gnnlab#11]
Hello, I would like to inquire about how gnnlab implements the full-neighborhood sampling for GCN models in CUDA. Unlike programs like GraphSAGE that allow specifying the size of the output array, it is difficult to determine the size of the node neighborhood in advance for GCN models. However, CUDA requires knowing the size of the output array. Therefore, I am curious to know how you have addressed this issue. I apologize for the large codebase, which makes it challenging for me to locate the exact implementation details in gnnlab.

**Comment by molamooo** [comment]
GNNLab currently does not provide an implementation of full-neighbor sampling. You may have to implement it on your own.

**Comment by BearBiscuit05** [comment]
Thanks for the response. If gnnlab does not implement full-neighbor sampling, then during training of the GCN model, does the sampling function directly use the MultiLayerFullNeighborSampler() function from dgl? Or is there any other implementation approach?

**Comment by molamooo** [comment]
GNNLab trains GCN with neighbour sampling similar to GraphSAGE, only with different settings of hop & num of neighbour.

**Comment by BearBiscuit05** [comment]
Thank you very much for your response. I understand.
