### ISSUE TITLE
Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method

### ISSUE THREAD

**Issue by a1bc2def6g** [SJTU-IPADS/gnnlab#12]
When running the dgl on multi-gpu, the code (example/dgl/multi_gpu/train_gcn.py) you provide raise an error as the title. Is the version or some other issues? Thanks!

**Comment by molamooo** [comment]
Can you describe in detail how you build the environment and deploy GNNLab?

**Comment by a1bc2def6g** [comment]
Thanks to your reply! Yes. I don't use the docker and perform the installation as the README.md on 3090 GPU. The software versions in my enviroment are as follows:
1. CUDA v11.3
2. DGL v1.0.0
3. fastgraph v0.2.0
4. Python v3.7
5. PyTorch v1.10.1

**Comment by lixiaobai09** [comment]
Did you change the code of GNNLab? I guess you may modify some lines of code to run in 3090. If changes the code, you should make sure no CUDA functions are called before the fork.

And if you give us your original error logs information, it will be more helpful to address this problem.

**Comment by a1bc2def6g** [comment]
yeah, I modify some lines and I have fixed this bug by use the torch.multiprocessing instead of dgl.multiprocessing, thanks!

**Comment by molamooo** [comment]
Good to know. I'll close this issue as it's solved. You may reopen it if you encounter any further problem.
