### ISSUE TITLE
Check failed: (data) != ((void *)-1)"

### ISSUE THREAD

**Issue by lzc17** [SJTU-IPADS/gnnlab#16]
There is an error ‘gnnlab/samgraph/common/common.cc:99] Check failed: (data) != ((void *)-1)’.The output filepath is shown below:
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/6c0edffb-111a-4579-8323-ad5234aabaf3)

**Comment by molamooo** [comment]
We need more information help you solve this. For example, your deployment environmenet and method, how you generated the dataset, and the full log.

**Comment by lzc17** [comment]
The data set is processed according to "datagen/README.md", and the processed files are as follows:
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/2f400195-6eef-41e0-b678-19245df62c40)

**Comment by lzc17** [comment]
The location of the running python file is:/home/liuzhencheng/gnnlab/gnnlab/example/samgraph/multi_gpu/train_graphsage.py

**Comment by lzc17** [comment]
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/d724ff6f-7e94-4fd1-a666-86f1b44e814c)

**Comment by lzc17** [comment]
It feels like the datapath accepted by c++ has become garbled.

**Comment by lzc17** [comment]
conda list ：
![Uploading image.png…]()

**Comment by molamooo** [comment]
I think the datapath is fine since samgraph successfully find `meta.txt` before raising this error.
We still need more information to solve this issue. Can you print filepath and errno before line99 in `common.cc`?

**Comment by lzc17** [comment]
Code added location:
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/f5386abf-a40c-4f5e-932b-3db27e4c8c32)

The output is as follows:
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/3831d039-7784-4fee-b607-cd232cafb210)

This file actually exists.

**Comment by molamooo** [comment]
What about errno? It might be the limit of locked memory. Can you provide the output of `ulimit -a` and `ulimit -aH`?

**Comment by lzc17** [comment]
ulimiit -a:
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/d031d677-2f41-4b65-90b2-6809855de370)
ulimit -aH:
![image](https://github.com/SJTU-IPADS/gnnlab/assets/41893135/d139b100-26c8-4f3d-869b-1b0095f7b84c)

**Comment by molamooo** [comment]
It is required that "max memory size" exceeds the size of graph, feature and graph samples. Follow GNNLab's [readme](https://github.com/SJTU-IPADS/gnnlab/tree/main#change-ulimit) to check and increase this limit.
