### ISSUE TITLE
raise an error when compile the data-process 

### ISSUE THREAD

**Issue by lh123cha** [SJTU-IPADS/gnnlab#17]
Hello,I want to download the UK dataset with the script uk-2006-05.sh.And the program raise an error:
```Bash
uk-2006-05.sh: line 45: ../utility/data-process/build/coo-to-dataset: No such file or directory
``` 
So I compile the /utility/data-process. And it raise 
```Bash
In file included from /home/lianghui/Projects/DUCTI/gnnlab/utility/data-process/toolkit/cache/cache_by_degree.cc:26:
/home/lianghui/Projects/DUCTI/gnnlab/utility/data-process/./common/options.h:21:10: fatal error: CLI/App.hpp: No such file or directory
   21 | #include <CLI/App.hpp>
      |          ^~~~~~~~~~~~~

``` 
How Can I ran the uk-2006-05.sh successful？

**Comment by lixiaobai09** [comment]
Maybe you do not pull all submodules for the gnnlab repository, especially for the "CLI11" submodule. You can clone this repository with option `--recursive`, like `git clone --recursive https://github.com/SJTU-IPADS/gnnlab.git`, or pull all submodules in the root directory of gnnlab repository with the command `git submodule update --init --recursive`.

**Comment by lh123cha** [comment]
I clone the repo with --recursive option.And I compile the data-process successfully.But I encounter the error :
![屏幕截图 2023-12-11 153657](https://github.com/SJTU-IPADS/gnnlab/assets/48644550/86f49b42-6aae-4abb-92d2-f5c7394b86b1)

**Comment by molamooo** [comment]
We need more information to identify the root cause. Can you provide the call stack when the segfault happens using debug tools like GDB?

**Comment by lh123cha** [comment]
Thank you for the answer!I have solved the problem.
