### ISSUE TITLE
A question about paper results

### ISSUE THREAD

**Issue by swordfate** [SJTU-IPADS/gnnlab#2]
Hello,  I am a little confused about the result in the picture as follows.
![tmp](https://user-images.githubusercontent.com/47095443/168019752-34d4544f-f9a9-4aa8-8a2d-034490796d26.jpg)

1. According to the description of GNNLab paper, TSOTA follows a time sharing design, i.e., each GPU conducts both graph sampling and model training, and adopts the degree-based caching policy. My question is **if each GPU stores the topology of the entire graph, and then use the remaining space to cache features of some nodes**?
2. According to my understanding, **GNNlab may use fewer GPUs in the Training stage than those used by DGL or TSOTA** (Because some GPUs are sometimes used to execute Sampler). **Why is the Train time (the red box on the far right) similar to DGL or TSOTA rather than higher?**

I would be very grateful if you could give any explanations :)

**Comment by molamooo** [comment]
1. Yes, all GPU stores a copy of graph topology, and use remaining space to do cache and train.
2. This table presents runtime breakdown, which uses only 1 gpu for sampling and 1 gpu for extract+training. You may see that time in this table is much slower in Table-4, which uses all 8 GPU.

**Comment by swordfate** [comment]
> 1. Yes, all GPU stores a copy of graph topology, and use remaining space to do cache and train.
> 2. This table presents runtime breakdown, which uses only 1 gpu for sampling and 1 gpu for extract+training. You may see that time in this table is much slower in Table-4, which uses all 8 GPU.

Thank you for your timely reply.
I'm sorry that I may not describe question 2 clearly. I want to know if DGL and TSOTA also use 2 GPUs. If so, more GPUs participated in GNN computing of DGL and TSOTA than GNNLab. Why the Train Time of one epoch for GNNLab is similar?

**Comment by molamooo** [comment]
DGL and TSOTA only uses 1 GPU, while GNNLab use 2 gpu. This may sounds unfair, but it's the best way to represent the breakdown of each stage in the end-2-end test. If still confusing, you may think from a batch's perspective, rather than an entire epoch. In the end-2-end test with all 8 GPU used, DGL and TSOTA use 1 GPU to do all 3 stage of one batch, while GNNLab uses 2 gpu.

**Comment by swordfate** [comment]
> DGL and TSOTA only uses 1 GPU, while GNNLab use 2 gpu. This may sounds unfair, but it's the best way to represent the breakdown of each stage in the end-2-end test. If still confusing, you may think from a batch's perspective, rather than an entire epoch. In the end-2-end test with all 8 GPU used, DGL and TSOTA use 1 GPU to do all 3 stage of one batch, while GNNLab uses 2 GPU.

OK, I got it! Your reply is very helpful. Thanks!
By the way,  Do the Sampling and Extracting time in the table denote **the remaining time that cannot be overlapped by pipeline** ?

**Comment by molamooo** [comment]
In DGL and TSOTA, 3 stage is executed in sequential, so there is no overlapping and no waste on compute power. In GNNLab's breakdown test, we aim to measure the time spent on each stage, so no need to do pipeline. In GNNLab's end-2-end test, sampler GPU is much less than trainer GPU. So, even if the time bewteen sample & extract+train not balanced, the assignment of less sampler GPU avoids wasting of compute power, so the time is nicely overlapped. For those extremely imbalanced case, we proposed the "Dynamic Switch" solution, and there is corresponding tests in the rest of the paper.

**Comment by swordfate** [comment]
> In DGL and TSOTA, 3 stage is executed in sequential, so there is no overlapping and no waste on compute power. In GNNLab's breakdown test, we aim to measure the time spent on each stage, so no need to do pipeline. In GNNLab's end-2-end test, sampler GPU is much less than trainer GPU. So, even if the time bewteen sample & extract+train not balanced, the assignment of less sampler GPU avoids wasting of compute power, so the time is nicely overlapped. For those extremely imbalanced case, we proposed the "Dynamic Switch" solution, and there is corresponding tests in the rest of the paper.

Oh,so it is. I got wrong before. Do you mean that neither the existing DGL and TSOTA can perform these 3 stages in parallel? So the results in Table 1 are also implemented in sequential? Then, what about the PyG?
![tmp-table1](https://user-images.githubusercontent.com/47095443/168036193-e46addcf-9275-4971-8198-69beec63c7af.jpg)

**Comment by molamooo** [comment]
Not sure about details in DGL. In TSOTA, 3 stages are not absolutely sequential, since we use different cuda stream to do these stages, and compute resource should not be wasted. There really isn't much space for parallelizing 3 stage **on one gpu**, since all 3 stage uses non-trivial compute resources. In table1, stages are reported in sequential with stream synchronization. In later end-2-end test, further overlapping of cuda stream is adopted.

As for PyG, it uses CPU to do sampling and GPU to do training, and we only have end-2-end test for it, which naturally adopts the pipeline method, since they are at different device.

**Comment by swordfate** [comment]
> Not sure about details in DGL. In TSOTA, 3 stages are not absolutely sequential, since we use different cuda stream to do these stages, and compute resource should not be wasted. There really isn't much space for parallelizing 3 stage **on one gpu**, since all 3 stage uses non-trivial compute resources. In table1, stages are reported in sequential with stream synchronization. In later end-2-end test, further overlapping of cuda stream is adopted.
> 
> As for PyG, it uses CPU to do sampling and GPU to do training, and we only have end-2-end test for it, which naturally adopts the pipeline method, since they are at different device.

Thank you again for your detailed and patient reply. I will continue to study this great job with its code. :)
