### ISSUE TITLE
Questions about the results of Table 1

### ISSUE THREAD

**Issue by A-Gentle-Cat** [SJTU-IPADS/gnnlab#20]
Hello and thank you for your excellent open source work. I am having problems trying to reproduce the experiment in Table 1, on my machine (Intel Xeon Gold 6148 60vCPU, 1*v100) I tested the CPU sampling capability of DGL-0.7.1 with your script and got the breakdown result as:
    Sample: 26.6s; Extract: 15.90s; Train: 6.20s; Total: 49.18s
which seems to be several times slower than your results, and my results are close to yours when sampling with DGL's GPU:
    Sample: 2.56s; extract: 14.32s; train: 5.88s; total: 22.84s.
Could you please share what you think might be the possible reasons for my slow DGL CPU sampling? Thank you very much.

**Comment by lixiaobai09** [comment]
Different CPU types we used may cause this result. You can try a V100 GPU platform in aliyun to reproduce the CPU sampling results.

**Comment by A-Gentle-Cat** [comment]
Thank you for your answer. One more question. I compared version 0.7.1 of dgl with your dgl.patch and found a large performance difference in the sampling process. I noticed that you made some modifications to dgl using dgl.patch, could you briefly describe the purpose of the modifications and the impact on performance in sampling process? Thank you very much!

**Comment by lixiaobai09** [comment]
The dgl path is used to load the dataset with CSC format.
