### ISSUE TITLE
Is the hot cached embeddings in each GPU the same?

### ISSUE THREAD

**Issue by swordfate** [SJTU-IPADS/gnnlab#4]
Both SOTA and GNNLab systems cache some hot embeddings in multiple GPUs. **I am curious whether embeddings that cached in each GPU are the same?** For example, two of ten embeddings will be cached in 2 GPUs; how many embeddings are to be cached in each GPU?

Thank you for taking the time to answer my questions. :)

**Comment by molamooo** [comment]
Yes, caches in each gpu are identical. This is because GNNLab uses single global queue between sampler & trainer, so the distribution of probability to access each vertex is identical between all trainers(since we are training a lot of epochs, the randomness is hidden)

**Comment by swordfate** [comment]
> Yes, caches in each gpu are identical. This is because GNNLab uses single global queue between sampler & trainer, so the distribution of probability to access each vertex is identical between all trainers(since we are training a lot of epochs, the randomness is hidden)

I  got it, thanks for your explanation. I close this issue first.
