### ISSUE TITLE
/graph-learning/utility/data-process/common/options.h:21:10: fatal error: CLI/App.hpp: No such file or directory

### ISSUE THREAD

**Issue by LukeLIN-web** [SJTU-IPADS/gnnlab#6]
https://github.com/SJTU-IPADS/gnnlab/blob/2d0dd92ce4e2efec3d47212ce73358cd03f8d3d8/datagen/README.md?plain=1#L127
I use `docker pull gnnlab/fgnn:v1.0` 
 
```shell
/graph-learning/utility/data-process/build# make 32to64 -j
Scanning dependencies of target 32to64
[ 25%] Building CXX object CMakeFiles/32to64.dir/toolkit/generator/32to64.cc.o
[ 50%] Building CXX object CMakeFiles/32to64.dir/common/graph_loader.cc.o
[ 75%] Building CXX object CMakeFiles/32to64.dir/common/options.cc.o
In file included from /graph-learning/utility/data-process/common/options.cc:18:0:
/graph-learning/utility/data-process/common/options.h:21:10: fatal error: CLI/App.hpp: No such file or directory
 #include <CLI/App.hpp>
          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by molamooo** [comment]
Our code base depends on a git submodule named CLI. You should go to the root folder of gnnlab git repo and run `git submodule update --init --recursive`. But why do you have source file located at `/graph-learning`? The image should already contain a clone of gnnlab repo at `/app/source`

**Comment by LukeLIN-web** [comment]
> Our code base depends on a git submodule named CLI. You should go to the root folder of gnnlab git repo and run `git submodule update --init --recursive`. But why do you have source file located at `/graph-learning`? The image should already contain a clone of gnnlab repo at `/app/source`

Thank you for your reply,  I use `docker run --ulimit memlock=-1 --rm --gpus all -v /root/gnnlab:/graph-learning -it gnnlab/fgnn:v1.0 bash` to start docker container so that I have source file located at `/graph-learning`
