### ISSUE TITLE
 Check failed: (data) != ((void *)-1) 

### ISSUE THREAD

**Issue by FXTY** [SJTU-IPADS/gnnlab#8]
Hello, when I run this project, the problem of samgraph/common/common.cc:99] Check failed: (data) != ((void *)-1) appears. Have you ever encountered it? If Can you tell me how you solved it?

**Comment by lixiaobai09** [comment]
Hello, this seems that there are some problems with your datasets. Have you downloaded a dataset entirely and run with it? You can print the `filepath` in `common.cc:97` to check it.

You can see [datagen/README.md](https://github.com/SJTU-IPADS/gnnlab/blob/main/datagen/README.md) to find out how to preprocess datasets.

**Comment by FXTY** [comment]
Thanks, I solved the problem with your advice.
